# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  bxEngine_config = debug
endif
ifeq ($(config),release)
  bxEngine_config = release
endif

PROJECTS := bxEngine

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

bxEngine:
ifneq (,$(bxEngine_config))
	@echo "==== Building bxEngine ($(bxEngine_config)) ===="
	@${MAKE} --no-print-directory -C bxEngine -f Makefile config=$(bxEngine_config)
endif

clean:
	@${MAKE} --no-print-directory -C bxEngine -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   bxEngine"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"