# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  juno_engine_config = debug
endif
ifeq ($(config),release)
  juno_engine_config = release
endif

PROJECTS := juno_engine

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

juno_engine:
ifneq (,$(juno_engine_config))
	@echo "==== Building juno_engine ($(juno_engine_config)) ===="
	@${MAKE} --no-print-directory -C juno_engine -f Makefile config=$(juno_engine_config)
endif

clean:
	@${MAKE} --no-print-directory -C juno_engine -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   juno_engine"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"